# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=b'news-images')),
                ('title', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True, editable=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
    ]
